#' run SQUiD function without graphical user interface
#'
#' @description          simulate a world inhabited by individuals whose phenotypes are generated by a user-defined 
#'                       phenotypic equation and then sampling from this world according to user-defined sampling design.
#' 
#' @param input          list of the model variables.
#' @param module         character of the module name when used with SQUID shiny app.
#'
#' @return               list with a data.frame of the full data generated and a data.frame 
#'                       of the sampled data.
#' @export
#' @example 
#' runSQUIDfct()
#'
runSQUIDfct <- function(input=list(), module="", shinyUI = FALSE){ 
  
  # Main function of the full model that simulates individual phenotypes over time
  # and then samples within those phenotypes according to specific sampling design
  #
  # Args:
  #   input: list contains all the inputs used to run the model 
  #          (for more details see setEnvironments and setVariables functions).
  #   module: name of the module.
  
  # Returns:
  #   Return a list with:
  #     full_Data   : continous phenotypic data (raw data)
  #     sampled_Data: sampled phenotypic data
  #     myPlot      : plots of the simulation results
  
  ##############################################################
  #################### INPUT VARIABLES  ########################
  ##############################################################  
  
  # Set up environmental variables
  environments <- setEnvironments(input, module)
  
  # Set up other variables
  variables <- setVariables(input, module, environments)
  
  Mu        <- variables$Mu
  N         <- variables$N
  B         <- variables$B
  V         <- variables$V
  Time      <- variables$Time
  variables <- variables$Variables
  
  # Initialize output
  output <- list()
  
  #######################################################################################
  ## Generate my phenotype traits
  output[["full_Data"]]    <- getFullData(Mu, N, B, r, V, Time, variables, environments)
  
  ####################################################################################### 
  ## Get Sampling data  
  output[["sampled_Data"]] <- getSampledData(N, Time, output[["full_Data"]])
  
  #######################################################################################
  ## Display results
  if(shinyUI) 
    output[["myPlot"]]     <- displayResults(N, Time, output[["full_Data"]], output[["sampled_Data"]])
  
  #######################################################################################

  return(output)
  
}