#' run SQUID without graphical user interface
#'
#' @description          simulate a world inhabited by individuals whose phenotypes are generated by a user-defined 
#'                       phenotypic equation and then sampling from this world according to user-defined sampling design.
#' 
#' @param input          list of the model input paramters (see details section).
#' @param module         character of the module name. This argument is only used by SQUID app.
#' @param plot           logical value. When TRUE plots of the results are included into the output list.
#' @param X_previsualization character of the environment names. This argument is only used by SQUID app.
#'
#' @return               list with a data.frame of the full data generated and a data.frame 
#'                       of the sampled data.
#'                       
#' @import data.table
#' @export
#' 
runSQUIDfct <- function(input=list(), module=NULL, plot=FALSE, X_previsualization=NULL){ 
  
  # Main function of the full model that simulates individual phenotypes over time
  # and then samples within those phenotypes according to specific sampling design
  #
  # Args:
  #   input: list contains all the inputs used to run the model 
  #          (for more details see setEnvironments and setVariables functions).
  #   module: name of the module.
  
  # Returns:
  #   Return a list with:
  #     full_Data   : continous phenotypic data (raw data)
  #     sampled_Data: sampled phenotypic data
  #     myPlot      : plots of the simulation results
  
  ##############################################################
  #################### INPUT VARIABLES  ########################
  ##############################################################  
  
  # Set seperator character
  sep <- ifelse(is.null(module), "", "_")
  
  # Set up environmental variables
  environments <- setEnvironments(input, module, sep)
  
  # Set up other variables
  variables    <- setVariables(input, module, environments, sep)
  
  Mu        <- variables$Mu
  N         <- variables$N
  B         <- variables$B
  V         <- variables$V
  Time      <- variables$Time
  variables <- variables$Variables
  
  if(is.null(X_previsualization)){
    
    # Initialize output
    output <- list()
    
    #######################################################################################
    ## Generate my phenotype traits
    output[["full_Data"]]    <- getFullData(Mu, N, B, r, V, Time, variables, environments)
    
    ####################################################################################### 
    ## Get Sampling data  
    output[["sampled_Data"]] <- getSampledData(N, Time, output[["full_Data"]])
    
    #######################################################################################
    ## Display results
    if(plot) 
      output[["myPlot"]]     <- displayResults(N, Time, output[["full_Data"]], output[["sampled_Data"]])
    
    #######################################################################################
    
  }else{
    
    if(X_previsualization %in% c("X1", "X2")){
      ### Generate environment for previsualization
      X <- getEnvironment(environments[[X_previsualization]], N, TRUE)
      
      myData   <- data.frame("envData"  = X, 
                             "x"        = rep(1:N$NS, N$NI),
                             "colour"   = as.factor(rep(1:N$NI, each = N$NS)))
      
      output   <- ggplot2::ggplot(myData, ggplot2::aes(y=envData, x=x, colour=colour)) +
                                  ggplot2::geom_point() +
                                  ggplot2::xlab("Time") +
                                  ggplot2::ylab("Environment") + 
                                  ggplot2::theme(legend.position="none")
    }else{
      stop("X_previsualization is not a valid environment tag.")
    }
  }
  
  return(output)
  
}